#!/usr/bin/env python3
"""Generate FakeLua headless fixtures for the fake2d gameplay demos.

Fake2d gameplay scripts only expose update(dt); they expect the engine's
native functions. To exercise their real logic without a window/GPU we
concatenate one chunk per demo:

    m_head.lua (native API stubs + embedded real Tiled grids)
    + scripts/<demo>.lua
    + m_tail.lua (scenario driver: runs N frames, asserts log codes)

The stubs are generated from the actual C++ bindings
(src/script/script_bindings.cpp) so argument counts always match what the
JIT's exact-arity checks require, and from the real assets/*.json maps so
tile/slope/entity logic runs against production level data.

FakeLua quirks handled here (verified against all three backends):
  * chunk-level locals must be initialised (no bare `local x`);
  * tables created while the file chunk initialises are const; persistent
    table locals therefore start nil (via a function call) and are created
    inside fix_boot(), which the driver invokes from main();
  * numeric table keys are normalised to floats (generic table opcode);
  * native calls are exact-arity, so generated stubs mirror C++ signatures.

Usage:
    python3 generate_fixtures.py --repo /path/to/fake2d --out /tmp/fix
"""

import argparse
import json
import re
from pathlib import Path

# --------------------------------------------------------------------- grids

def load_grid(repo: Path, asset: str):
    data = json.loads((repo / "assets" / asset).read_text())
    layer = next(l for l in data["layers"] if l["type"] == "tilelayer")
    gids = layer["data"]
    assert len(gids) == data["width"] * data["height"], asset
    csv = ",".join(str(int(v)) for v in gids)
    return data["width"], data["height"], csv


# ------------------------------------------------------------ C++ signatures

BIND_RE = re.compile(
    r'state,\s*"(\w+)",\s*false,\s*std::function<\s*([\w:]+)\s*\(([^)]*)\)\s*>',
    re.S,
)


def parse_native_api(bindings: Path):
    """name -> (cpp return type, lua-visible argument count)."""
    text = bindings.read_text()
    api = {}
    for m in BIND_RE.finditer(text):
        name, ret, params = m.group(1), m.group(2), m.group(3)
        args = [p.strip() for p in params.split(",")] if params.strip() else []
        args = [p for p in args if p != "fakelua::State *"]
        api[name] = (ret.strip(), len(args))
    return api


# ------------------------------------------------------------------- prelude

def build_prelude(mario_grid, plat_grid, slope_grid):
    mw, mh, mg = mario_grid
    pw, ph, pg = plat_grid
    sw, sh, sg = slope_grid

    return f'''-- AUTO-GENERATED by tests/headless/generate_fixtures.py - do not edit.
-- Headless native-API stubs concatenated ahead of a gameplay script.
-- C++ semantics mirrored: solid map gids are 1..9 and 14; entity handles
-- pack (generation << 32 | slot); entity enumeration is slot ordered.

-- Tables created during chunk init are const in FakeLua. Persistent table
-- locals start nil from a function call and are created in fix_boot()
-- (driver runs it from main). Numeric keys are forced to floats.
local function fix_nilval()
    return nil
end
local function fix_newtable()
    return {{}}
end
local function fix_tget(tab, key)
    return tab[key + 0.0]
end
local function fix_tset(tab, key, v)
    tab[key + 0.0] = v
end

-- ---------------------------------------------------------------- logs
local fix_logs = fix_nilval()
local fix_seen = fix_nilval()
local fix_nlog = 0 + 0

local function fix_rec(v)
    if fix_tget(fix_seen, v) ~= 1 then
        fix_nlog = fix_nlog + 1
        fix_tset(fix_logs, fix_nlog, v)
        fix_tset(fix_seen, v, 1)
    end
end

function log_number(v)
    fix_rec(v)
end

local function fix_has(code)
    if fix_tget(fix_seen, code) == 1 then return true end
    return false
end

local function fix_in_range(lo, hi)
    local i = 1
    while i <= fix_nlog do
        local v = fix_tget(fix_logs, i)
        if v >= lo and v <= hi then return true end
        i = i + 1
    end
    return false
end

-- ---------------------------------------------------------------- map
local fix_g_mario = "{mg}"
local fix_g_plat = "{pg}"
local fix_g_slope = "{sg}"
local fix_cells = fix_nilval()
local fix_cols = 0 + 0
local fix_rows = 0 + 0
local fix_ncell = 0 + 0
local fix_tile = 32 + 0

local function fix_load_grid(s, c, r)
    fix_cols = c
    fix_rows = r
    fix_ncell = 0
    for tok in string.gmatch(s, "%d+") do
        fix_ncell = fix_ncell + 1
        fix_tset(fix_cells, fix_ncell, tonumber(tok) + 0)
    end
end

function map_load(path)
    if path == "assets/mario.json" then
        fix_load_grid(fix_g_mario, {mw}, {mh})
    elseif path == "assets/platformer.json" then
        fix_load_grid(fix_g_plat, {pw}, {ph})
    elseif path == "assets/slope.json" then
        fix_load_grid(fix_g_slope, {sw}, {sh})
    else
        fix_load_grid(fix_g_mario, {mw}, {mh})
    end
    return 1
end

local function fix_gid(c, r)
    if c < 0 or r < 0 or c >= fix_cols or r >= fix_rows then return 0 end
    local g = fix_tget(fix_cells, r * fix_cols + c + 1)
    if g == nil then return 0 end
    return g
end

local function fix_solid_gid(g)
    if g >= 1 and g <= 9 then return true end
    if g == 14 then return true end
    return false
end

function map_draw(id) end
function map_cols(id) return fix_cols end
function map_rows(id) return fix_rows end
function map_tilew(id) return fix_tile end
function map_tileh(id) return fix_tile end
function map_tile(id, c, r) return fix_gid(c, r) end
function map_set_tile(id, c, r, g)
    if c >= 0 and r >= 0 and c < fix_cols and r < fix_rows then
        fix_tset(fix_cells, r * fix_cols + c + 1, g)
    end
end
function map_solid(id, c, r) return fix_solid_gid(fix_gid(c, r)) end
function map_oneway(id, c, r) return false end
function map_slope_dir(id, c, r) return 0 end
function map_slope_rise(id, c, r) return 0 end
function map_ground_y(id, wx, reach) return -1.0 end
function map_layer_count(id) return 1 end
function map_layer_parallax_x(id, i) return 1.0 end
function map_layer_parallax_y(id, i) return 1.0 end

-- ---------------------------------------------------------------- entities
local fix_ea = fix_nilval()
local fix_eg = fix_nilval()
local fix_et = fix_nilval()
local fix_en = fix_nilval()
local fix_elive = 0 + 0
local fix_GENBASE = 4294967296.0

local function fix_resolve(id)
    if id == nil then return -1 end
    if id <= 0 then return -1 end
    local g = math.floor(id / fix_GENBASE)
    local s = id - g * fix_GENBASE
    if s < 0 or s >= 256 then return -1 end
    if fix_tget(fix_ea, s) ~= 1 then return -1 end
    if fix_tget(fix_eg, s) ~= g then return -1 end
    return s
end

function ent_create(tag)
    local s = 0
    while s < 256 do
        if fix_tget(fix_ea, s) ~= 1 then
            fix_tset(fix_ea, s, 1)
            local g = fix_tget(fix_eg, s)
            if g == nil then g = 1 end
            fix_tset(fix_eg, s, g)
            fix_tset(fix_et, s, tag)
            fix_elive = fix_elive + 1
            return g * fix_GENBASE + s
        end
        s = s + 1
    end
    return 0
end

function ent_destroy(id)
    local s = fix_resolve(id)
    if s >= 0 then
        fix_tset(fix_ea, s, 0)
        fix_tset(fix_eg, s, fix_tget(fix_eg, s) + 1)
        fix_tset(fix_et, s, 0)
        fix_elive = fix_elive - 1
    end
end

function ent_clear()
    local s = 0
    while s < 256 do
        if fix_tget(fix_ea, s) == 1 then
            fix_tset(fix_ea, s, 0)
            fix_tset(fix_eg, s, fix_tget(fix_eg, s) + 1)
            fix_tset(fix_et, s, 0)
        end
        s = s + 1
    end
    fix_elive = 0
end

function ent_active(id)
    if fix_resolve(id) >= 0 then return true end
    return false
end

function ent_tag(id)
    local s = fix_resolve(id)
    if s < 0 then return 0 end
    local t = fix_tget(fix_et, s)
    if t == nil then return 0 end
    return t
end

function ent_set_tag(id, tag)
    local s = fix_resolve(id)
    if s >= 0 then fix_tset(fix_et, s, tag) end
end

function ent_num(id, slot)
    local s = fix_resolve(id)
    if s < 0 then return 0 end
    local v = fix_tget(fix_en, s * 8.0 + slot)
    if v == nil then return 0 end
    return v
end

function ent_set_num(id, slot, v)
    local s = fix_resolve(id)
    if s >= 0 then fix_tset(fix_en, s * 8.0 + slot, v) end
end

function ent_str(id, slot) return "" end
function ent_set_str(id, slot, v) end

function ent_count(tag)
    local n = 0
    local s = 0
    while s < 256 do
        if fix_tget(fix_ea, s) == 1
            and (tag < 0 or fix_tget(fix_et, s) == tag) then
            n = n + 1
        end
        s = s + 1
    end
    return n
end

function ent_at(index, tag)
    local n = 0
    local s = 0
    while s < 256 do
        if fix_tget(fix_ea, s) == 1
            and (tag < 0 or fix_tget(fix_et, s) == tag) then
            if n == index then
                return fix_tget(fix_eg, s) * fix_GENBASE + s
            end
            n = n + 1
        end
        s = s + 1
    end
    return 0
end

-- ---------------------------------------------------------------- sprites
local fix_texn = 0 + 0
function sprite_load(path)
    fix_texn = fix_texn + 1
    return fix_texn
end
function sprite_free(h) end
function sprite_width(h) return 32 end
function sprite_height(h) return 32 end
function sprite_draw(h, x, y, w, hh) end
function sprite_draw_tinted(h, x, y, w, hh, r, g, b, a) end
function sprite_draw_region(h, sx, sy, sw, sh, dx, dy, dw, dh) end
function sprite_draw_rotated(h, sx, sy, sw, sh, dx, dy, dw, dh, a0, a1, a2) end
function sprite_draw_flip(h, sx, sy, sw, sh, dx, dy, dw, dh, fx, fy) end

-- ---------------------------------------------------------------- input
function input_key_down(k) return false end
function input_key_pressed(k) return false end
function input_key_released(k) return false end
function input_mouse_x() return 0.0 end
function input_mouse_y() return 0.0 end
function input_mouse_down(b) return false end
function input_mouse_pressed(b) return false end
function input_mouse_wheel() return 0.0 end
function input_pad_connected(ix) return false end
function input_pad_down(ix, b) return false end
function input_pad_pressed(ix, b) return false end
function input_pad_released(ix, b) return false end
function input_pad_axis(ix, a) return 0.0 end
function input_pad_name(ix) return "" end

-- ---------------------------------------------------------------- time
function time_delta() return 1.0 / 60.0 end
function time_elapsed() return 0.0 end
function time_frame() return 0 end

-- ---------------------------------------------------------------- camera
local fix_camx = 0.0 + 0.0
local fix_camy = 0.0 + 0.0
function camera_set_position(x, y) fix_camx = x; fix_camy = y end
function camera_move(x, y) end
function camera_set_zoom(z) end
function camera_set_rotation(r) end
function camera_x() return fix_camx end
function camera_y() return fix_camy end
function camera_zoom() return 1.0 end
function camera_rotation() return 0.0 end
function camera_screen_to_world_x(x, y) return x end
function camera_screen_to_world_y(x, y) return y end
function camera_world_to_screen_x(x, y) return x end
function camera_world_to_screen_y(x, y) return y end
function camera_shake(a) end
function camera_viewport_w() return 960.0 end
function camera_viewport_h() return 540.0 end

-- ---------------------------------------------------------------- draw
function draw_line(a, b, c, d, e, f, g, h) end
function draw_rect_outline(a, b, c, d, e, f, g, h) end
function draw_circle_outline(a, b, c, d, e, f, g, h) end
function draw_quad(a, b, c, d, e, f, g, h) end
function draw_quad_rgb(a, b, c, d, e, f, g) end
function draw_text(s, x, y, sc, r, g, b, a) return 0.0 end
function text_width(s, sc) return 0.0 end
function draw_set_layer(a) end
function draw_set_z(a) end
function draw_set_blend(a) end
function draw_use_shader(id) end

-- ---------------------------------------------------------------- audio
function audio_play(name, vol) end
function audio_enabled() return true end
function audio_music(path, vol) end
function audio_music_stop() end

-- ---------------------------------------------------------------- particles
function part_create() return 1 end
function part_set_lifetime(h, a, b) end
function part_set_speed(h, a, b) end
function part_set_direction(h, a, b) end
function part_set_size(h, a, b) end
function part_set_color(h, r, g, b, a, x) end
function part_set_gravity(h, a, b) end
function part_set_drag(h, a) end
function part_set_spin(h, a) end
function part_emit(h, n, x, y) end
function part_draw() end

-- ---------------------------------------------------------------- shaders
function shader_load(v, f) return 1 end
function shader_destroy(id) end
function shader_set_float(id, name, v) end
function shader_set_int(id, name, v) end
function shader_set_vec2(id, name, x, y) end
function shader_set_vec4(id, name, x, y, z, w) end

-- ---------------------------------------------------------------- storage
local fix_have = 0 + 0
local fix_bs = 0.0 + 0.0
local fix_bt = 0.0 + 0.0
function storage_load(slot)
    if fix_have == 1 then return true end
    return false
end
function storage_save(slot) fix_have = 1; return true end
function storage_set_num(k, v)
    if k == "best_score" then fix_bs = v
    elseif k == "best_time" then fix_bt = v end
end
function storage_get_num(k, dflt)
    if k == "best_score" then return fix_bs
    elseif k == "best_time" then return fix_bt end
    if dflt == nil then return 0 end
    return dflt
end
function storage_set_str(k, v) end
function storage_get_str(k, dflt)
    if dflt == nil then return "" end
    return dflt
end
function storage_has(k) return false end
function storage_delete(k) end
function storage_reset() end

-- ---------------------------------------------------------------- window / ui
local fix_quit = 0 + 0
function window_quit() fix_quit = 1 end
function window_set_title(t) end
function window_set_fullscreen(b) end
function window_fullscreen() return false end
function ui_panel(a, b, c, d, e, f, g, h, i) end
function ui_label(a, b, c, d, e, f, g, h, i) end
function ui_button(a, b, c, d, e, f, g, h) return false end
function ui_set_origin(a, b) end

-- Reset every persistent state slot. Defined last so all locals above are
-- in scope; the driver calls this once from main().
function fix_boot()
    fix_logs = fix_newtable()
    fix_seen = fix_newtable()
    fix_cells = fix_newtable()
    fix_ea = fix_newtable()
    fix_eg = fix_newtable()
    fix_et = fix_newtable()
    fix_en = fix_newtable()
    fix_nlog = 0
    fix_cols = 0
    fix_rows = 0
    fix_ncell = 0
    fix_elive = 0
    fix_texn = 0
    fix_camx = 0.0
    fix_camy = 0.0
    fix_quit = 0
    fix_have = 0
    fix_bs = 0.0
    fix_bt = 0.0
end
'''


TAIL = '''-- AUTO-GENERATED driver tail. Scenario selected by FIX_SCENARIO.

local function fix_expect(code, label, fails)
    if fix_has(code) then
        print("PASS " .. label)
    else
        print("FAIL " .. label .. " (missing " .. string.format("%d", code) .. ")")
        fails = fails + 1
    end
    return fails
end

local function fix_expect_range(lo, hi, label, fails)
    if fix_in_range(lo, hi) then
        print("PASS " .. label)
    else
        print("FAIL " .. label .. " (no code in " .. string.format("%d", lo)
              .. ".." .. string.format("%d", hi) .. ")")
        fails = fails + 1
    end
    return fails
end

local function fix_forbid(code, label, fails)
    if fix_has(code) then
        print("FAIL " .. label .. " (unexpected " .. string.format("%d", code) .. ")")
        fails = fails + 1
    else
        print("PASS " .. label)
    end
    return fails
end

function main()
    fix_boot()
    local sc = os.getenv("FIX_SCENARIO")
    local frames = 300
    local fr = os.getenv("FIX_FRAMES")
    if fr ~= nil then frames = tonumber(fr) end
    local i = 0
    while i < frames do
        update(1.0 / 60.0)
        i = i + 1
    end

    local fails = 0
    if sc == "mario_smoke" then
        fails = fix_expect(900112, "mario: map loads 112 cols", fails)
        fails = fix_expect(201001, "mario: mode stays PLAY", fails)
        fails = fix_expect(204080, "mario: idle player holds spawn px=80", fails)
        fails = fix_forbid(300010, "mario: no goomba death", fails)
        fails = fix_forbid(300011, "mario: no pit death", fails)
        fails = fix_forbid(300012, "mario: no timeout death", fails)
    elseif sc == "mario_death" then
        fails = fix_expect(300004, "mario: death sequence finished", fails)
        fails = fix_expect(301002, "mario: one life spent (lives=2)", fails)
    elseif sc == "mario_win" then
        fails = fix_expect(300005, "mario: pole touch starts win", fails)
        fails = fix_expect(300021, "mario: slide reaches ground", fails)
        fails = fix_expect(300022, "mario: walk reaches castle -> clear", fails)
        fails = fix_expect_range(300023, 304000, "mario: time bonus banked", fails)
    elseif sc == "mario_die3" then
        fails = fix_expect(301000, "mario: third death reaches GAME OVER", fails)
        fails = fix_expect(840000, "mario: reopen restores lives/score/tiles/goombas", fails)
    elseif sc == "mario_phys" then
        fails = fix_expect_range(820000, 820999, "mario PHYS: walk plateau ~150", fails)
        fails = fix_expect_range(821000, 821999, "mario PHYS: full-hop apex ~130px", fails)
        fails = fix_expect_range(822000, 822999, "mario PHYS: run plateau ~235", fails)
    elseif sc == "mario_blocks" then
        fails = fix_expect(830001, "mario BLOCKS: ? block becomes USED", fails)
        fails = fix_expect(830002, "mario BLOCKS: USED block does not retrigger", fails)
        fails = fix_expect(830003, "mario BLOCKS: mid block spawns mushroom", fails)
        fails = fix_expect(830004, "mario BLOCKS: mushroom grows player", fails)
        fails = fix_expect(830007, "mario BLOCKS: bonk kills goomba above", fails)
        fails = fix_expect(830005, "mario BLOCKS: big form breaks brick", fails)
        fails = fix_expect_range(830006, 830106, "mario BLOCKS: bump offset anim played", fails)
    elseif sc == "slope_smoke" then
        fails = fix_expect(900001, "slope: lab initializes", fails)
        fails = fix_expect_range(900000, 900099, "slope: feet trace logs", fails)
    else
        print("PASS platformer: " .. string.format("%d", frames) .. " frames ran clean")
    end

    print("FAILURES " .. string.format("%d", fails))
    return fails
end
'''

DEFAULTS = {
    "void": None,
    "bool": "false",
    "double": "0.0",
    "std::int64_t": "0",
    "std::string": '""',
}


def emit_default_stub(name, ret, arity):
    args = ", ".join(f"a{i}" for i in range(1, arity + 1))
    if DEFAULTS[ret] is None:
        return f"function {name}({args}) end"
    return f"function {name}({args}) return {DEFAULTS[ret]} end"


def write_fixtures(repo: Path, out: Path):
    out.mkdir(parents=True, exist_ok=True)
    api = parse_native_api(repo / "src" / "script" / "script_bindings.cpp")

    prelude = build_prelude(
        load_grid(repo, "mario.json"),
        load_grid(repo, "platformer.json"),
        load_grid(repo, "slope.json"),
    )

    # Every hand-written stub must match the C++ binding arity exactly.
    for m in re.finditer(r"^function (\w+)\(([^)]*)\)", prelude, re.M):
        name, arglist = m.group(1), m.group(2).strip()
        if name.startswith("fix_"):
            continue
        nargs = 0 if not arglist else len(arglist.split(","))
        assert name in api, f"stub {name} not present in C++ bindings"
        assert api[name][1] == nargs, (
            f"{name}: C++ arity {api[name][1]} vs stub {nargs}")

    custom = {m.group(1) for m in
              re.finditer(r"^function (\w+)\(", prelude, re.M)
              if not m.group(1).startswith("fix_")}

    auto = ["-- ---------------------------------------------- unused engine API"]
    for name, (ret, _arity) in sorted(api.items()):
        if name not in custom:
            auto.append(emit_default_stub(name, ret, _arity))

    (out / "m_head.lua").write_text(prelude + "\n" + "\n".join(auto) + "\n",
                                   newline="\n")
    (out / "m_tail.lua").write_text(TAIL, newline="\n")
    return len(custom), len(api) - len(custom)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()
    n_custom, n_auto = write_fixtures(args.repo, args.out)
    print(f"fixtures written to {args.out} "
          f"(custom stubs: {n_custom}, auto defaults: {n_auto})")


if __name__ == "__main__":
    main()
