-- fake2d pure-Lua platformer demo (--platformer-demo).
--
-- A complete scrolling level driven entirely by this script: a kinematic
-- AABB character controller (run, variable jumps, coyote time, jump
-- buffering, one-way platforms), tile-rewrite coin pickups, a goal flag,
-- a trauma-shake follow camera and debug line overlays.
--
-- Controls: A/D or arrows to move, Space/W/Up to jump. In headless mode a
-- deterministic attract AI runs to the right.
--
-- Tileset/level JSON/player sprite/music WAV are generated by the host
-- binary; all game rules live below.

-- gids in the generated tileset (firstgid = 1)
local G_GRASS, G_DIRT, G_PLANK, G_COIN, G_GOAL, G_BACK = 1, 2, 3, 4, 5, 6

-- tuning (mirrors the classic platformer feel kit)
local HALF_W, HALF_H = 10.0, 15.0
local RUN_SPEED = 200.0
local GROUND_ACCEL, AIR_ACCEL = 2200.0, 1300.0
local GROUND_FRICTION = 2000.0
local GRAVITY, MAX_FALL = 1500.0, 560.0
local JUMP_V = 430.0
local JUMP_CUT = 0.45
local COYOTE, JUMP_BUFFER = 0.09, 0.12

local map_id = 0 + 0
local player_tex = 0 + 0
local inited = false

local px, py = 0.0 + 0.0, 0.0 + 0.0   -- top-left of the player box
local vx, vy = 0.0 + 0.0, 0.0 + 0.0
local on_ground = false
local facing = 1 + 0
local coyote_t = 0.0 + 0.0
local buffer_t = 0.0 + 0.0
local cut_used = false
local jump_hold = 0 + 0
local coins = 0 + 0
local total_coins = 0 + 0
local win_timer = -1 + 0

local cols, rows, tile = 0 + 0, 0 + 0, 32 + 0

-- Known coin cells (match the generated level). Numeric file locals because
-- FakeLua file-level tables are read-only.
local cc1, cc2, cc3, cc4 = 6, 12, 16, 22
local cc5, cc6, cc7, cc8 = 26, 33, 10, 24
local cr1, cr2, cr3, cr4 = 10, 8, 10, 7
local cr5, cr6, cr7, cr8 = 9, 6, 13, 12
local GOAL_COL, GOAL_ROW = 38, 14
local N_COINS = 8

local function coin_col(i)
    if i == 1 then return cc1 elseif i == 2 then return cc2
    elseif i == 3 then return cc3 elseif i == 4 then return cc4
    elseif i == 5 then return cc5 elseif i == 6 then return cc6
    elseif i == 7 then return cc7 end
    return cc8
end

local function coin_row(i)
    if i == 1 then return cr1 elseif i == 2 then return cr2
    elseif i == 3 then return cr3 elseif i == 4 then return cr4
    elseif i == 5 then return cr5 elseif i == 6 then return cr6
    elseif i == 7 then return cr7 end
    return cr8
end

local function clampf(v, lo, hi)
    if v < lo then return lo end
    if v > hi then return hi end
    return v
end

local function spawn()
    px = 2.0 * tile
    py = 13.0 * tile
    vx, vy = 0.0, 0.0
    on_ground = false
    coyote_t, buffer_t = 0.0, 0.0
    cut_used = false
    win_timer = -1
    coins = 0
    -- Restore collectibles from their known level positions.
    for i = 1, N_COINS do
        map_set_tile(map_id, coin_col(i), coin_row(i), G_COIN)
    end
    map_set_tile(map_id, GOAL_COL, GOAL_ROW, G_GOAL)
end

-- Highest walkable surface under the box footprint (solids + slopes), -1 none.
local function ground_hint(nx, reach)
    local g = map_ground_y(map_id, nx + 2.0, reach)
    local gm = map_ground_y(map_id, nx + HALF_W, reach)
    local gf = map_ground_y(map_id, nx + HALF_W * 2.0 - 2.0, reach)
    if gm >= 0.0 and (g < 0.0 or gm < g) then g = gm end
    if gf >= 0.0 and (g < 0.0 or gf < g) then g = gf end
    return g
end

-- Horizontal swept move; slope cells are never walls, and surface lips up
-- to 8px are stepped onto automatically.
local function move_x(dx)
    local nx = px + dx
    local c0 = math.floor(nx / tile)
    local c1 = math.floor((nx + HALF_W * 2.0 - 0.01) / tile)
    local r0 = math.floor(py / tile)
    local r1 = math.floor((py + HALF_H * 2.0 - 0.01) / tile)
    local wall_top = -1.0
    for r = r0, r1 do
        for c = c0, c1 do
            if map_slope_dir(map_id, c, r) == 0 and map_solid(map_id, c, r) then
                local top = r * tile
                if wall_top < 0.0 or top < wall_top then wall_top = top end
            end
        end
    end
    local feet = py + HALF_H * 2.0
    if wall_top >= 0.0 and wall_top < feet - 8.0 then
        -- Too tall to step: reject the move (legacy solid wall behavior).
        if dx > 0.0 then
            px = c0 * tile - HALF_W * 2.0
        else
            px = (c1 + 1) * tile
        end
        vx = 0.0
        return
    end
    px = nx
    if vy >= 0.0 then
        local lift = wall_top
        local g = ground_hint(px, feet + 8.0)
        if g >= 0.0 and (lift < 0.0 or g < lift) then lift = g end
        if lift >= 0.0 and lift < feet and feet - lift <= 8.0 then
            py = lift - HALF_H * 2.0
        end
    end
end

-- Vertical swept move; feet_bottom is the pre-move bottom (one-way test).
-- Returns downward landing speed (>0 means a landing happened).
local function move_y(dy, feet_before)
    py = py + dy
    local c0 = math.floor((px + 0.5) / tile)
    local c1 = math.floor((px + HALF_W * 2.0 - 0.5) / tile)
    local r0 = math.floor(py / tile)
    local r1 = math.floor((py + HALF_H * 2.0) / tile)
    for r = r0, r1 do
        for c = c0, c1 do
            local solid = map_solid(map_id, c, r)
            local oneway = map_oneway(map_id, c, r)
            if solid or oneway then
                local tile_top = r * tile
                if dy > 0.0 then
                    -- one-way only catches when feet were above the top
                    if oneway and not solid and feet_before > tile_top + 0.5 then
                        -- pass through
                    else
                        local impact = vy
                        py = tile_top - HALF_H * 2.0
                        vy = 0.0
                        return impact
                    end
                elseif dy < 0.0 and solid then
                    py = (r + 1) * tile
                    vy = 0.0
                    return 0.0
                end
            end
        end
    end
    -- Slope fallback (slope tiles are not solid AABBs): snap down onto a
    -- reachable surface while falling. Upward steps are handled in move_x.
    if dy > 0.0 then
        local feet_now = py + HALF_H * 2.0
        local g = ground_hint(px, feet_now + 6.0)
        if g >= 0.0 and g <= feet_now + 6.0 and g >= feet_now - 2.0 then
            local impact = vy
            py = g - HALF_H * 2.0
            vy = 0.0
            return impact
        end
    end
    return 0.0
end

local function center()
    return px + HALF_W, py + HALF_H
end

local function step_player(dt, intent_x, jump_pressed, jump_held)
    if intent_x > 0.1 then facing = 1 end
    if intent_x < -0.1 then facing = -1 end

    -- horizontal accel / friction
    local target = intent_x * RUN_SPEED
    if math.abs(intent_x) > 0.1 then
        local rate = GROUND_ACCEL
        if not on_ground then rate = AIR_ACCEL end
        if vx < target then
            vx = math.min(target, vx + rate * dt)
        elseif vx > target then
            vx = math.max(target, vx - rate * dt)
        end
    elseif on_ground then
        if vx > 0.0 then vx = math.max(0.0, vx - GROUND_FRICTION * dt)
        else vx = math.min(0.0, vx + GROUND_FRICTION * dt) end
    end

    -- coyote + buffer
    if jump_pressed then buffer_t = JUMP_BUFFER else buffer_t = buffer_t - dt end
    if on_ground then coyote_t = COYOTE else coyote_t = coyote_t - dt end

    local jumped = false
    if buffer_t > 0.0 and coyote_t > 0.0 then
        vy = -JUMP_V
        on_ground = false
        coyote_t = 0.0
        buffer_t = 0.0
        cut_used = false
        jumped = true
    end
    if not jump_held and vy < 0.0 and not cut_used then
        vy = vy * JUMP_CUT
        cut_used = true
    end

    vy = math.min(MAX_FALL, vy + GRAVITY * dt)

    -- substepped integration
    local dx, ddy = vx * dt, vy * dt
    local n = math.ceil(math.max(math.abs(dx), math.abs(ddy)) / 12.0)
    if n < 1 then n = 1 end
    local sdx, sdy = dx / n, ddy / n
    local impact = 0.0
    for i = 1, n do
        move_x(sdx)
        local feet_before = py + HALF_H * 2.0
        local hit = move_y(sdy, feet_before)
        if sdy > 0.0 and hit > 0.0 then
            on_ground = true
            impact = hit
        end
    end

    -- ground probe (keeps on_ground true across flat runs)
    if vy >= 0.0 then
        local supported = false
        local feet = py + HALF_H * 2.0
        local probe = feet + 1.5
        local c = math.floor((px + HALF_W) / tile)
        local r = math.floor(probe / tile)
        if map_solid(map_id, c, r) then
            supported = true
        elseif map_oneway(map_id, c, r) and probe - 1.5 <= r * tile + 0.5 then
            supported = true
        end
        if not supported then
            local gs = ground_hint(px, feet + 1.5)
            if gs >= 0.0 and math.abs(gs - feet) <= 2.0 then
                supported = true
            end
        end
        on_ground = supported
    end
    return jumped, impact
end

-- No frame parameter on purpose: FakeLua JIT specializes local functions by
-- argument type, and a typed-arg specialization of a multi-value return fails
-- codegen. time_frame() is read inside so the function stays generic.
local function build_intent()
    local frame = time_frame()
    local move = 1.0
    if input_key_down("left") or input_key_down("a") then move = -1.0 end
    if input_key_down("right") or input_key_down("d") then move = 1.0 end

    local cx, cy = center()
    local feet_row = math.floor((cy + HALF_H + 4.0) / tile)
    local ahead = math.floor((cx + HALF_W + 20.0) / tile)

    -- Tile coordinates for probes are precomputed: arithmetic sitting
    -- directly in a call's last-argument slot hits a JIT codegen bug.
    local up_row = feet_row - 1
    local down_row = feet_row + 1
    local wall = map_solid(map_id, ahead, feet_row)
    if map_solid(map_id, ahead, up_row) then wall = true end
    local gap = not map_solid(map_id, ahead, down_row)
    local below_oneway = map_oneway(map_id, ahead, down_row)
    if below_oneway then gap = false end
    local coin_ahead = false
    for dc = 0, 3 do
        for dr = -4, 0 do
            local tc = ahead + dc
            local tr = feet_row + dr
            if map_tile(map_id, tc, tr) == G_COIN then
                coin_ahead = true
            end
        end
    end

    local key_jump = input_key_pressed("space") or input_key_pressed("w")
        or input_key_pressed("up")
    local ai_jump = wall or (on_ground and gap) or coin_ahead or (frame % 80 == 0)
    local pressed = key_jump or (ai_jump and jump_hold == 0)
    if pressed then jump_hold = 12 end
    local held = jump_hold > 0
    if jump_hold > 0 then jump_hold = jump_hold - 1 end
    return move, pressed, held
end

local function collect_coins()
    local cx, cy = center()
    for dr = -1, 1 do
        for dc = -1, 1 do
            local c = math.floor(cx / tile) + dc
            local r = math.floor(cy / tile) + dr
            if map_tile(map_id, c, r) == G_COIN then
                map_set_tile(map_id, c, r, G_BACK)
                coins = coins + 1
                audio_play("coin", 0.35)
            end
        end
    end
end

local function draw_debug(cam_x, cam_y, vw, vh)
    draw_rect_outline(px, py, HALF_W * 2.0, HALF_H * 2.0, 0.3, 0.9, 1.0, 0.9)
    local c0 = math.max(0, math.floor(cam_x / tile))
    local c1 = math.min(cols - 1, math.floor((cam_x + vw) / tile))
    local r0 = math.max(0, math.floor(cam_y / tile))
    local r1 = math.min(rows - 1, math.floor((cam_y + vh) / tile))
    for r = r0, r1 do
        for c = c0, c1 do
            local tx, ty = c * tile, r * tile
            if map_oneway(map_id, c, r) then
                draw_line(tx, ty + 5.0, tx + tile, ty + 5.0, 0.5, 1.0, 0.6, 0.8)
            end
            if map_tile(map_id, c, r) == G_COIN then
                draw_circle_outline(tx + 16, ty + 16, 13, 16, 1.0, 0.9, 0.4, 0.8)
            end
            if map_tile(map_id, c, r) == G_GOAL then
                draw_rect_outline(tx + 2, ty + 2, 28, 28, 0.5, 1.0, 0.6, 0.8)
            end
        end
    end
end

function update(dt)
    if not inited then
        inited = true
        map_id = map_load("assets/platformer.json")
        player_tex = sprite_load("assets/player.png")
        cols = map_cols(map_id)
        rows = map_rows(map_id)
        tile = map_tilew(map_id)
        total_coins = N_COINS
        spawn()
        audio_music("music", 0.22)
    end

    local intent_x, jump_pressed, jump_held = build_intent()

    local jumped, impact = step_player(dt, intent_x, jump_pressed, jump_held)
    if jumped then audio_play("jump", 0.12) end
    if impact > 220.0 then
        -- Hoisted out of the camera_shake() argument: a slow-path binop in a
        -- call's last-argument slot hits a JIT codegen bug.
        local shake_amt = impact / 1200.0
        if shake_amt > 0.5 then shake_amt = 0.5 end
        camera_shake(shake_amt)
    end

    local cx, cy = center()
    if cy > rows * tile + 60.0 then spawn() end

    collect_coins()

    local goal_c = math.floor(cx / tile)
    local goal_r = math.floor(cy / tile)
    if map_tile(map_id, goal_c, goal_r) == G_GOAL
        and win_timer < 0 then
        win_timer = 0
        camera_shake(0.7)
        audio_play("win", 0.4)
    end
    if win_timer >= 0 then
        win_timer = win_timer + 1
        if win_timer > 180 then spawn() end
    end

    -- follow camera (clamp bounds precomputed, same reason as shake_amt)
    local vw, vh = camera_viewport_w(), camera_viewport_h()
    local map_w, map_h = cols * tile, rows * tile
    local max_x = map_w - vw
    if max_x < 0.0 then max_x = 0.0 end
    local max_y = map_h - vh
    if max_y < -20.0 then max_y = -20.0 end
    local want_x = cx - vw * 0.5
    local want_y = cy - vh * 0.55
    local cam_x = clampf(want_x, 0.0, max_x)
    local cam_y = clampf(want_y, -20.0, max_y)
    camera_set_position(cam_x, cam_y)

    map_draw(map_id)
    sprite_draw(player_tex, px - 2.0, py - 2.0, 24.0, 34.0)
    draw_debug(cam_x, cam_y, vw, vh)

    -- world-anchored HUD
    ui_set_origin(cam_x, cam_y)
    ui_label(0, cam_x + 16, cam_y + 12, "COINS " .. coins .. "/" .. total_coins,
             0.6, 0.96, 0.90, 0.51, 1.0)
    ui_label(0, cam_x + 16, cam_y + 38, "A/D MOVE  SPACE JUMP", 0.4,
             0.67, 0.71, 0.80, 1.0)
    if ui_button("restart", 0, cam_x + vw - 126.0, cam_y + 10.0, 110.0, 32.0,
                 "RESTART", 0.5) then
        spawn()
    end
    if win_timer >= 0 then
        local banner = "LEVEL COMPLETE!"
        local w = text_width(banner, 1.4)
        draw_text(banner, cam_x + vw * 0.5 - w * 0.5,
                  cam_y + vh * 0.5 - 40.0, 1.4, 0.47, 0.92, 0.55, 1.0)
    end
    return 0
end
