-- fake2d pure-Lua scene showcase (--scene-demo).
-- Everything you see is driven from this script: tinted sprites orbit a
-- pivot and spin, a frame animation plays, a particle emitter sparkles,
-- and anchored text/panels are drawn. Assets (PNGs) are generated by the
-- host binary; this file contains all of the demo logic.

local W, H = 960, 540

local brick_tex = 0 + 0
local paddle_tex = 0 + 0
local ball_tex = 0 + 0
local coin_tex = 0 + 0
local coin_anim = 0 + 0
local spark_fx = 0 + 0
local inited = false

local function init_assets()
    brick_tex = sprite_load("assets/brick.png")
    paddle_tex = sprite_load("assets/paddle.png")
    ball_tex = sprite_load("assets/ball.png")
    coin_tex = sprite_load("assets/coin.png")

    coin_anim = anim_create()
    anim_frame(coin_anim, coin_tex, 0, 0, 16, 16)
    anim_frame(coin_anim, coin_tex, 16, 0, 16, 16)
    anim_frame(coin_anim, coin_tex, 32, 0, 16, 16)
    anim_frame(coin_anim, coin_tex, 48, 0, 16, 16)
    anim_fps(coin_anim, 9)
    anim_loop(coin_anim, true)
    anim_play(coin_anim)

    spark_fx = part_create()
    part_set_lifetime(spark_fx, 0.4, 0.9)
    part_set_speed(spark_fx, 20, 90)
    part_set_direction(spark_fx, 0, 6.28)
    part_set_size(spark_fx, 4, 1)
    part_set_gravity(spark_fx, 0, 0)
    part_set_drag(spark_fx, 0.6)
    part_set_spin(spark_fx, 4)
    part_set_color(spark_fx, 1.0, 0.85, 0.4, 1.0, 0.0)
end

-- Orbiting sprite slots (file-level table is runtime-constant state).
local orbiters = {
    {tex = 0, size = 56.0, ring = 150.0, speed = 0.9, phase = 0.0, spin = 1.6, r = 0.95, g = 0.35, b = 0.35},
    {tex = 0, size = 48.0, ring = 150.0, speed = 0.9, phase = 1.05, spin = -2.1, r = 0.4, g = 0.9, b = 0.5},
    {tex = 0, size = 64.0, ring = 150.0, speed = 0.9, phase = 2.1, spin = 1.1, r = 0.45, g = 0.6, b = 1.0},
    {tex = 0, size = 42.0, ring = 235.0, speed = -0.55, phase = 0.4, spin = 2.6, r = 1.0, g = 0.8, b = 0.3},
    {tex = 0, size = 52.0, ring = 235.0, speed = -0.55, phase = 2.5, spin = -1.8, r = 0.75, g = 0.45, b = 0.95},
    {tex = 1, size = 130.0, ring = 0.0, speed = 0.0, phase = 0.0, spin = 0.5, r = 0.7, g = 0.85, b = 1.0}
}

local function draw()
    local t = time_elapsed()
    draw_quad(0, 0, W, H, 0.05, 0.06, 0.10, 1.0)

    -- info panel (top left)
    ui_panel(0, 16, 16, 250, 86, 0.13, 0.17, 0.27, 0.92)
    ui_label(0, 28, 26, "SCENE SHOWCASE - PURE LUA", 0.55, 0.92, 0.95, 1.0, 1.0)
    ui_label(0, 28, 52, "sprites * rotation * particles * text", 0.4, 0.65, 0.72, 0.9, 1.0)
    ui_label(0, 28, 74, "frame " .. time_frame(), 0.4, 0.5, 0.57, 0.75, 1.0)

    -- ground band with a bright line
    draw_quad(0, H - 56, W, 56, 0.10, 0.13, 0.20, 1.0)
    draw_line(0, H - 56, W, H - 56, 0.3, 0.5, 0.8, 0.7)

    local cx, cy = W * 0.5, H * 0.52

    -- additive sparkle cloud around the pivot
    draw_set_blend(1)
    part_emit(spark_fx, 2, cx + math.cos(t * 0.8) * 150,
              cy + math.sin(t * 0.8) * 150)
    part_draw()
    draw_set_blend(0)

    -- orbiters: tinted textured quads positioned on rings, each spinning.
    for i = 1, 6 do
        local o = orbiters[i]
        local tex = brick_tex
        if o.tex == 1 then tex = paddle_tex end
        local ang = t * o.speed + o.phase
        local x = cx + math.cos(ang) * o.ring - o.size * 0.5
        local y = cy + math.sin(ang) * o.ring - o.size * 0.5
        if o.tex == 1 then
            sprite_draw(tex, x, y, o.size, o.size * 0.28)
        else
            sprite_draw_rotated(tex, 0, 0, 86, 26, x, y, o.size, o.size,
                                t * o.spin, o.size * 0.5, o.size * 0.5)
        end
        -- orbit guide
        if o.ring > 0 then
            draw_circle_outline(cx, cy, o.ring, 48, 0.25, 0.35, 0.55, 0.25)
        end
    end

    -- center ball + debug outline
    sprite_draw(ball_tex, cx - 11, cy - 11, 22, 22)
    draw_circle_outline(cx, cy, 16, 24, 0.4, 0.9, 1.0, 0.8)

    -- spinning coin chip, top right
    anim_draw(coin_anim, W - 60, 22, 26, 26)
    draw_rect_outline(W - 66, 16, 38, 38, 1.0, 0.85, 0.4, 0.5)

    -- pulsing hint
    if math.sin(t * 4.0) > 0 then
        local hint = "all drawing issued from scene_demo.lua"
        local hw = text_width(hint, 0.5)
        draw_text(hint, W * 0.5 - hw * 0.5, H - 38, 0.5,
                  0.75, 0.82, 0.95, 0.85)
    end
end

function update(dt)
    if not inited then
        inited = true
        init_assets()
    end
    draw()
    return 0
end
